In [1]:
import pickle
import os

import pandas as pd

from interpret import show
from interpret.glassbox import ExplainableBoostingClassifier

RESULTS_DIR = "../"
EXPLANATION_X = "../data/100000samples-4blobs/4blobs-X_explain.csv"
EXPLANATION_Y = "../data/100000samples-4blobs/4blobs-Y_explain.csv"

TRAIN_X = "../data/100000samples-4blobs/4blobs-X_train.csv"
TRAIN_Y = "../data/100000samples-4blobs/4blobs-Y_train.csv"

In [2]:
x_train = pd.read_csv(TRAIN_X, header=None, names=["X", "Y"])
y_train = pd.read_csv(TRAIN_Y, header=None, names=["prediction"])

x_explain = pd.read_csv(EXPLANATION_X, header=None, names=["X", "Y"])
y_explain = pd.read_csv(EXPLANATION_Y, header=None, names=["prediction"])

x_train, y_train

(               X          Y
 0      14.652694   5.075718
 1       2.117643  14.972409
 2       1.961905  15.227716
 3       1.625918  16.021119
 4       1.741271   4.632720
 ...          ...        ...
 59995   1.766203   4.851097
 59996  15.015112  14.822512
 59997   1.819251  15.432938
 59998   1.990780   5.511430
 59999  15.518059  15.161977
 
 [60000 rows x 2 columns],
        prediction
 0               1
 1               1
 2               1
 3               1
 4               0
 ...           ...
 59995           0
 59996           0
 59997           1
 59998           0
 59999           0
 
 [60000 rows x 1 columns])

In [3]:
ebm = ExplainableBoostingClassifier(feature_names=["X", "Y"], feature_types=['continuous', 'continuous',
                                             'categorical'])
ebm.fit(x_train, y_train)

ExplainableBoostingClassifier(feature_names=['X', 'Y', 'X x Y'],
                              feature_types=['continuous', 'continuous',
                                             'interaction'])

In [4]:
show(ebm.explain_global())

/home/robert/anaconda3/lib/python3.8/site-packages/interpret/visual/udash.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
/home/robert/anaconda3/lib/python3.8/site-packages/interpret/visual/udash.py:6: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/home/robert/anaconda3/lib/python3.8/site-packages/interpret/visual/udash.py:7: UserWarning: 
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table as dt


<!-- http://127.0.0.1:7001/140626994030048/ -->

In [5]:
show(ebm.explain_local(x_explain, y_explain))

<!-- http://127.0.0.1:7001/140627499616384/ -->

In [8]:
y_explain_pred = ebm.predict(x_explain)
y_explain_pred

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [16]:
import numpy as np
y_explain.values == y_explain_pred

array([[ True,  True, False, ..., False,  True, False],
       [ True,  True, False, ..., False,  True, False],
       [False, False,  True, ...,  True, False,  True],
       ...,
       [False, False,  True, ...,  True, False,  True],
       [ True,  True, False, ..., False,  True, False],
       [False, False,  True, ...,  True, False,  True]])

In [17]:
y_explain.values.shape

(100, 1)

In [19]:
x1 = np.squeeze(y_explain.values)
x2 = np.squeeze(y_explain_pred)

x1 == x2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [20]:
np.where(x1 != x2)

(array([42, 55]),)